Downgrade conda-build on appveyor because of symlink issues
Error:
libarchive.exception.ArchiveError: Can't create '\\?\C:\bld\tmp1bwudd5q\lazygit-0.6\vendor\github.com\hashicorp\go-getter\test-fixtures\detect-file-symlink-pwd\syml\pwd' (errno=22, retcode=-25, archive_p=894540077248)

See also: https://github.com/conda/conda-build/issues/3351